theme: jekyll-theme-minimal
title: Computationally Efficient, Low-Latency, Low-Energy Models
description: a mathematical optimization library to increase computational efficiency of ML models.
markdown: kramdown
kramdown:
  input: GFM